name: Build and Test
on: [push, pull_request]
jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    if: ${{ !startsWith(github.ref_name, 'mac') && !startsWith(github.ref_name, 'windows') }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - postgres: 16
            os: ubuntu-22.04
          - postgres: 15
            os: ubuntu-22.04
    steps:
      - uses: ankane/setup-postgres@v1
        with:
          postgres-version: ${{ matrix.postgres }}
          dev-files: true
          config: |
            jit_above_cost=0
            jit=on
            jit_provider='asmjit'
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: |
          git clone https://github.com/postgres/postgres -b REL_${{ matrix.postgres }}_STABLE
      - run: make
        env:
          PG_CFLAGS: -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare
      - run: |
          export PG_CONFIG=`which pg_config`
          sudo --preserve-env=PG_CONFIG make install
      - run: |
          sudo chown -R postgres:postgres postgres
          cd postgres
          sudo -u postgres "$(pwd)"/configure --prefix=/usr/lib/postgresql/${{ matrix.postgres }}
          sudo -u postgres make installcheck
      - if: ${{ failure() }}
        run: cat postgres/src/test/regress/regression.diffs
